
-- FASE 19.1 — Perfil Público: 6 tabelas + RLS + triggers + função de leitura pública
-- Idempotente (IF NOT EXISTS / DROP POLICY IF EXISTS antes de CREATE POLICY)
-- Rollback pronto em supabase/rollback/fase_19_perfil_publico.sql

-- ============================================
-- 1. TABELAS
-- ============================================

CREATE TABLE IF NOT EXISTS public_profile (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE,
  slug text NOT NULL UNIQUE CHECK (slug ~ '^[a-z0-9-]{3,40}$'),
  is_active boolean NOT NULL DEFAULT false,
  agent_enabled boolean NOT NULL DEFAULT true,
  cta_texto text DEFAULT 'Fale agora',
  cta_tipo text DEFAULT 'chat' CHECK (cta_tipo IN ('chat','whatsapp')),
  video_youtube_url text,
  youtube_canal_url text,
  show_agent_online_badge boolean NOT NULL DEFAULT true,
  headline text,
  subheadline text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public_services (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nome text NOT NULL,
  descricao text,
  foto_url text,
  preco_text text,
  ordem integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_public_services_user_ordem
  ON public_services(user_id, ordem);

CREATE TABLE IF NOT EXISTS public_gallery (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  titulo text,
  descricao text,
  foto_url text NOT NULL,
  ordem integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_public_gallery_user_ordem
  ON public_gallery(user_id, ordem);

CREATE TABLE IF NOT EXISTS public_testimonials (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  autor_nome text NOT NULL,
  autor_foto_url text,
  texto text NOT NULL,
  nota smallint CHECK (nota BETWEEN 1 AND 5),
  aprovado boolean NOT NULL DEFAULT false,
  aprovado_at timestamptz,
  rag_chunk_id uuid REFERENCES knowledge_chunks(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_public_testimonials_user_aprovado
  ON public_testimonials(user_id, aprovado, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_public_testimonials_rag_chunk
  ON public_testimonials(rag_chunk_id) WHERE rag_chunk_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public_chat_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_token uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  lead_id uuid REFERENCES leads(id) ON DELETE SET NULL,
  conversation_id uuid REFERENCES conversations(id) ON DELETE SET NULL,
  visitor_name text,
  visitor_phone text,
  visitor_email text,
  ip_hash text,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_activity_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_public_chat_sessions_user_activity
  ON public_chat_sessions(user_id, last_activity_at DESC);
CREATE INDEX IF NOT EXISTS idx_public_chat_sessions_lead
  ON public_chat_sessions(lead_id) WHERE lead_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_public_chat_sessions_conversation
  ON public_chat_sessions(conversation_id) WHERE conversation_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public_profile_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  session_id uuid,
  event_type text NOT NULL CHECK (event_type IN (
    'page_view','cta_click','chat_started','chat_message',
    'lead_created','whatsapp_handoff','testimonial_submitted'
  )),
  metadata jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_public_profile_events_user_type_created
  ON public_profile_events(user_id, event_type, created_at DESC);

-- ============================================
-- 2. ALTER empresas (adiciona youtube)
-- ============================================

ALTER TABLE empresas ADD COLUMN IF NOT EXISTS youtube text;

-- ============================================
-- 3. updated_at trigger em public_profile
-- ============================================

CREATE OR REPLACE FUNCTION set_updated_at_public_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_public_profile_updated_at ON public_profile;
CREATE TRIGGER tg_public_profile_updated_at
BEFORE UPDATE ON public_profile
FOR EACH ROW EXECUTE FUNCTION set_updated_at_public_profile();

-- ============================================
-- 4. RLS
-- ============================================

ALTER TABLE public_profile          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public_services         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public_gallery          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public_testimonials     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public_chat_sessions    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public_profile_events   ENABLE ROW LEVEL SECURITY;

-- Dono autenticado: CRUD total nas próprias rows
DROP POLICY IF EXISTS "owner_all_public_profile" ON public_profile;
CREATE POLICY "owner_all_public_profile" ON public_profile
  FOR ALL TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "owner_all_public_services" ON public_services;
CREATE POLICY "owner_all_public_services" ON public_services
  FOR ALL TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "owner_all_public_gallery" ON public_gallery;
CREATE POLICY "owner_all_public_gallery" ON public_gallery
  FOR ALL TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "owner_all_public_testimonials" ON public_testimonials;
CREATE POLICY "owner_all_public_testimonials" ON public_testimonials
  FOR ALL TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

-- Visitante anônimo pode submeter testimonial apenas se perfil for público ativo
-- e sempre com aprovado=false (moderação obrigatória)
DROP POLICY IF EXISTS "anon_insert_public_testimonials" ON public_testimonials;
CREATE POLICY "anon_insert_public_testimonials" ON public_testimonials
  FOR INSERT TO anon
  WITH CHECK (
    aprovado = false
    AND aprovado_at IS NULL
    AND rag_chunk_id IS NULL
    AND EXISTS (
      SELECT 1 FROM public_profile pp
      WHERE pp.user_id = public_testimonials.user_id AND pp.is_active = true
    )
  );

-- Sessions e Events: dono só lê (INSERT/UPDATE via service_role em edges)
DROP POLICY IF EXISTS "owner_select_sessions" ON public_chat_sessions;
CREATE POLICY "owner_select_sessions" ON public_chat_sessions
  FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);

DROP POLICY IF EXISTS "owner_select_events" ON public_profile_events;
CREATE POLICY "owner_select_events" ON public_profile_events
  FOR SELECT TO authenticated
  USING ((SELECT auth.uid()) = user_id);

-- ============================================
-- 5. Função de leitura pública (SECURITY DEFINER)
-- ============================================

CREATE OR REPLACE FUNCTION public_get_profile(p_slug text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
STABLE
SET search_path = public, auth
AS $$
DECLARE
  v_user_id uuid;
  v_profile jsonb;
  v_empresa jsonb;
  v_services jsonb;
  v_gallery jsonb;
  v_testimonials jsonb;
BEGIN
  SELECT pp.user_id INTO v_user_id
  FROM public_profile pp
  WHERE pp.slug = p_slug AND pp.is_active = true;

  IF v_user_id IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT to_jsonb(pp) - 'user_id' INTO v_profile
  FROM public_profile pp WHERE pp.user_id = v_user_id;

  SELECT jsonb_build_object(
    'nome', e.nome,
    'descricao', e.descricao,
    'endereco', e.endereco,
    'bairro', e.bairro,
    'cidade', e.cidade,
    'estado', e.estado,
    'cep', e.cep,
    'instagram', e.instagram,
    'facebook', e.facebook,
    'tiktok', e.tiktok,
    'whatsapp', e.whatsapp,
    'youtube', e.youtube,
    'site', e.site,
    'logo_url', e.logo_url,
    'banner_url', e.banner_url
  ) INTO v_empresa
  FROM empresas e WHERE e.user_id = v_user_id LIMIT 1;

  SELECT coalesce(jsonb_agg(
    jsonb_build_object(
      'id', s.id, 'nome', s.nome, 'descricao', s.descricao,
      'foto_url', s.foto_url, 'preco_text', s.preco_text, 'ordem', s.ordem
    ) ORDER BY s.ordem
  ), '[]'::jsonb) INTO v_services
  FROM public_services s WHERE s.user_id = v_user_id;

  SELECT coalesce(jsonb_agg(
    jsonb_build_object(
      'id', g.id, 'titulo', g.titulo, 'descricao', g.descricao,
      'foto_url', g.foto_url, 'ordem', g.ordem
    ) ORDER BY g.ordem
  ), '[]'::jsonb) INTO v_gallery
  FROM public_gallery g WHERE g.user_id = v_user_id;

  SELECT coalesce(jsonb_agg(
    jsonb_build_object(
      'id', t.id, 'autor_nome', t.autor_nome, 'autor_foto_url', t.autor_foto_url,
      'texto', t.texto, 'nota', t.nota, 'created_at', t.created_at
    ) ORDER BY t.created_at DESC
  ), '[]'::jsonb) INTO v_testimonials
  FROM public_testimonials t
  WHERE t.user_id = v_user_id AND t.aprovado = true;

  RETURN jsonb_build_object(
    'profile', v_profile,
    'empresa', v_empresa,
    'services', v_services,
    'gallery', v_gallery,
    'testimonials', v_testimonials
  );
END;
$$;

REVOKE ALL ON FUNCTION public_get_profile(text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public_get_profile(text) TO anon, authenticated;

-- ============================================
-- 6. Trigger testimonial → knowledge_chunks (RAG)
-- ============================================

CREATE OR REPLACE FUNCTION public_testimonial_to_rag()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_agent_id uuid;
  v_chunk_id uuid;
  v_content text;
BEGIN
  -- Aprovou: cria chunk
  IF NEW.aprovado = true
     AND (TG_OP = 'INSERT' OR OLD.aprovado = false)
     AND NEW.rag_chunk_id IS NULL
  THEN
    SELECT id INTO v_agent_id
    FROM user_agents
    WHERE user_id = NEW.user_id AND is_active = true
    ORDER BY created_at DESC LIMIT 1;

    IF v_agent_id IS NOT NULL THEN
      v_content := NEW.autor_nome
        || CASE WHEN NEW.nota IS NOT NULL THEN ' (' || NEW.nota || '★)' ELSE '' END
        || ': ' || NEW.texto;

      INSERT INTO knowledge_chunks (agent_id, title, content, category, escopo, tipo, ativo)
      VALUES (
        v_agent_id,
        'Depoimento de ' || NEW.autor_nome,
        v_content,
        'prova_social',
        'tenant',
        'resposta_factual',
        true
      ) RETURNING id INTO v_chunk_id;

      NEW.rag_chunk_id := v_chunk_id;
      NEW.aprovado_at := now();
    END IF;
  END IF;

  -- Reprovou: remove chunk
  IF TG_OP = 'UPDATE'
     AND NEW.aprovado = false
     AND OLD.aprovado = true
     AND OLD.rag_chunk_id IS NOT NULL
  THEN
    DELETE FROM knowledge_chunks WHERE id = OLD.rag_chunk_id;
    NEW.rag_chunk_id := NULL;
    NEW.aprovado_at := NULL;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS tg_public_testimonial_to_rag ON public_testimonials;
CREATE TRIGGER tg_public_testimonial_to_rag
BEFORE INSERT OR UPDATE ON public_testimonials
FOR EACH ROW EXECUTE FUNCTION public_testimonial_to_rag();

-- Delete em cascata manual: se deletar testimonial, deleta o chunk RAG
CREATE OR REPLACE FUNCTION public_testimonial_delete_rag()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF OLD.rag_chunk_id IS NOT NULL THEN
    DELETE FROM knowledge_chunks WHERE id = OLD.rag_chunk_id;
  END IF;
  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS tg_public_testimonial_delete_rag ON public_testimonials;
CREATE TRIGGER tg_public_testimonial_delete_rag
AFTER DELETE ON public_testimonials
FOR EACH ROW EXECUTE FUNCTION public_testimonial_delete_rag();

;
