
-- Drop 50 wrappers RPC EN — funções equivalentes PT-BR já em uso pelo TS
DROP FUNCTION IF EXISTS public.apply_tag_merge(uuid, text);
DROP FUNCTION IF EXISTS public.approve_conversation_excerpt_to_rag(uuid, uuid, uuid[], text, text, uuid, uuid);
DROP FUNCTION IF EXISTS public.approve_testimonial_to_rag(uuid, uuid);
DROP FUNCTION IF EXISTS public.backfill_tag_candidates(uuid);
DROP FUNCTION IF EXISTS public.belief_resumo_tenant(uuid, integer);
DROP FUNCTION IF EXISTS public.buffer_incoming_message(text, uuid, uuid, text, text, text);
DROP FUNCTION IF EXISTS public.bulk_update_campaign_leads(uuid, uuid, uuid[], text);
DROP FUNCTION IF EXISTS public.check_and_increment_storage(uuid, bigint);
DROP FUNCTION IF EXISTS public.check_buffer_ready(text, uuid, integer);
DROP FUNCTION IF EXISTS public.check_public_rate_limit(text, text, integer);
DROP FUNCTION IF EXISTS public.check_rate_limit(text, text, integer, integer);
DROP FUNCTION IF EXISTS public.check_webhook_dedup(text, text, integer);
DROP FUNCTION IF EXISTS public.claim_message_buffer(text, uuid);
DROP FUNCTION IF EXISTS public.cleanup_expired_team_invitations();
DROP FUNCTION IF EXISTS public.dashboard_stats(uuid, timestamptz);
DROP FUNCTION IF EXISTS public.dashboard_work_data(uuid, timestamptz);
DROP FUNCTION IF EXISTS public.decrement_storage(uuid, bigint);
DROP FUNCTION IF EXISTS public.derive_tags_for_lead(uuid);
DROP FUNCTION IF EXISTS public.desativar_conversation_pause(uuid);
DROP FUNCTION IF EXISTS public.expire_subscriptions();
DROP FUNCTION IF EXISTS public.export_my_data();
DROP FUNCTION IF EXISTS public.get_campaign_metrics(uuid);
DROP FUNCTION IF EXISTS public.get_lead_ficha_completa(uuid);
DROP FUNCTION IF EXISTS public.get_my_parent_user_id();
DROP FUNCTION IF EXISTS public.get_public_client_documents(uuid);
DROP FUNCTION IF EXISTS public.get_public_empresa_data(uuid);
DROP FUNCTION IF EXISTS public.get_public_service_flow(uuid);
DROP FUNCTION IF EXISTS public.get_referral_owner_id();
DROP FUNCTION IF EXISTS public.get_storage_usage(uuid);
DROP FUNCTION IF EXISTS public.is_platform_admin();
DROP FUNCTION IF EXISTS public.load_agent_context(uuid);
DROP FUNCTION IF EXISTS public.log_contract_event(uuid, text, jsonb);
DROP FUNCTION IF EXISTS public.process_embedding_jobs(integer);
DROP FUNCTION IF EXISTS public.public_get_profile(text);
DROP FUNCTION IF EXISTS public.recalculate_storage(uuid);
DROP FUNCTION IF EXISTS public.refresh_conversas_usadas_cache(uuid);
DROP FUNCTION IF EXISTS public.release_conversation_lock(uuid);
DROP FUNCTION IF EXISTS public.remove_team_member(uuid);
DROP FUNCTION IF EXISTS public.request_account_deletion();
DROP FUNCTION IF EXISTS public.reset_subscription_cycle(uuid, integer);
DROP FUNCTION IF EXISTS public.resolve_referral_code(text);
DROP FUNCTION IF EXISTS public.set_buffer_composing(text, uuid, boolean);
DROP FUNCTION IF EXISTS public.set_contract_pdf_url_public(uuid, text);
DROP FUNCTION IF EXISTS public.set_custom_field(uuid, text, text);
DROP FUNCTION IF EXISTS public.set_tag_curadoria_intervalo(integer);
DROP FUNCTION IF EXISTS public.sign_contract_public(uuid, jsonb);
DROP FUNCTION IF EXISTS public.submit_payment_proof_public(uuid, text);
DROP FUNCTION IF EXISTS public.supersede_outbox_pendentes(uuid, timestamptz);
DROP FUNCTION IF EXISTS public.toggle_public_checkpoint(uuid, text, boolean);
DROP FUNCTION IF EXISTS public.try_conversation_lock(uuid, integer);

;
