
-- ============================================================
-- 006 CONFIG_OPTIONS
-- ============================================================

CREATE TABLE config_options (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  scope TEXT NOT NULL,
  value TEXT NOT NULL,
  label TEXT NOT NULL,
  description TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_default BOOLEAN NOT NULL DEFAULT false,
  is_active BOOLEAN NOT NULL DEFAULT true,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (scope, value)
);

COMMENT ON TABLE config_options IS 'Substituto de enums. Toda opcao configuravel vira registro aqui.';

INSERT INTO config_options (scope, value, label, sort_order, is_default) VALUES
  ('tenant_status', 'active', 'Ativo', 1, true),
  ('tenant_status', 'suspended', 'Suspenso', 2, false),
  ('tenant_status', 'deactivated', 'Desativado', 3, false),
  ('profile_status', 'active', 'Ativo', 1, true),
  ('profile_status', 'suspended', 'Suspenso', 2, false),
  ('profile_status', 'deactivated', 'Desativado', 3, false),
  ('invitation_status', 'pending', 'Pendente', 1, true),
  ('invitation_status', 'accepted', 'Aceito', 2, false),
  ('invitation_status', 'expired', 'Expirado', 3, false),
  ('invitation_status', 'cancelled', 'Cancelado', 4, false),
  ('agent_status', 'draft', 'Rascunho', 1, true),
  ('agent_status', 'active', 'Ativo', 2, false),
  ('agent_status', 'paused', 'Pausado', 3, false),
  ('agent_status', 'deactivated', 'Desativado', 4, false),
  ('flow_status', 'draft', 'Rascunho', 1, true),
  ('flow_status', 'active', 'Ativo', 2, false),
  ('flow_status', 'paused', 'Pausado', 3, false),
  ('lead_status', 'new', 'Novo', 1, true),
  ('lead_status', 'active', 'Ativo', 2, false),
  ('lead_status', 'completed', 'Concluido', 3, false),
  ('lead_status', 'abandoned', 'Abandonado', 4, false),
  ('conversation_status', 'active', 'Ativa', 1, true),
  ('conversation_status', 'ended', 'Encerrada', 2, false),
  ('conversation_status', 'transferred', 'Transferida', 3, false),
  ('message_role', 'user', 'Usuario', 1, false),
  ('message_role', 'assistant', 'Assistente', 2, false),
  ('message_role', 'system', 'Sistema', 3, false),
  ('handler_type', 'engine', 'Motor (IA)', 1, true),
  ('handler_type', 'human', 'Humano', 2, false),
  ('channel_type', 'whatsapp', 'WhatsApp', 1, false),
  ('channel_type', 'webchat', 'Chat Web', 2, true),
  ('channel_type', 'api', 'API', 3, false),
  ('billing_type', 'credits', 'Creditos', 1, true),
  ('billing_type', 'unlimited', 'Ilimitado', 2, false),
  ('credit_tx_type', 'purchase', 'Compra', 1, false),
  ('credit_tx_type', 'consumption', 'Consumo', 2, false),
  ('credit_tx_type', 'refund', 'Reembolso', 3, false),
  ('credit_tx_type', 'adjustment', 'Ajuste manual', 4, false),
  ('credit_tx_type', 'bonus', 'Bonus', 5, false),
  ('security_category', 'prompt_injection', 'Prompt Injection', 1, false),
  ('security_category', 'jailbreak', 'Jailbreak', 2, false),
  ('security_category', 'manipulation', 'Manipulacao', 3, false),
  ('security_category', 'hallucination', 'Alucinacao', 4, false),
  ('security_direction', 'input', 'Entrada', 1, false),
  ('security_direction', 'output', 'Saida', 2, false),
  ('security_direction', 'both', 'Ambos', 3, false),
  ('security_action', 'block', 'Bloquear', 1, false),
  ('security_action', 'flag', 'Sinalizar', 2, false),
  ('security_action', 'log_only', 'Apenas logar', 3, false),
  ('security_severity', 'low', 'Baixa', 1, false),
  ('security_severity', 'medium', 'Media', 2, false),
  ('security_severity', 'high', 'Alta', 3, false),
  ('security_severity', 'critical', 'Critica', 4, false),
  ('llm_provider', 'openai', 'OpenAI', 1, false),
  ('llm_provider', 'anthropic', 'Anthropic', 2, false),
  ('llm_provider', 'meta', 'Meta', 3, false),
  ('llm_provider', 'google', 'Google', 4, false),
  ('llm_provider', 'mistral', 'Mistral', 5, false),
  ('config_value_type', 'text', 'Texto', 1, false),
  ('config_value_type', 'integer', 'Inteiro', 2, false),
  ('config_value_type', 'boolean', 'Booleano', 3, false),
  ('config_value_type', 'json', 'JSON', 4, false),
  ('config_value_type', 'decimal', 'Decimal', 5, false),
  ('subscription_status', 'active', 'Ativa', 1, true),
  ('subscription_status', 'expired', 'Expirada', 2, false),
  ('subscription_status', 'cancelled', 'Cancelada', 3, false),
  ('subscription_status', 'suspended', 'Suspensa', 4, false);

;
