ALTER TABLE public.produtos
  ADD COLUMN IF NOT EXISTS chave_pix TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS link_pagamento TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS pagamento_a_vista BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS pagamento_parcelado BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS max_parcelas_sem_juros INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS max_parcelas_com_juros INTEGER NOT NULL DEFAULT 12,
  ADD COLUMN IF NOT EXISTS parcelas_juros_a_partir INTEGER NOT NULL DEFAULT 4,
  ADD COLUMN IF NOT EXISTS taxa_juros NUMERIC(5,2) NOT NULL DEFAULT 0;
;
