"""Teste de interface (sem banco) das telas do lote C2: Financeiro, Sócio e Consulta (admin). Abre o babel-os.html direto.
Uso: python3 backend/local/testes/teste-c2-telas.py  (servidor em http://127.0.0.1:8090)"""
from playwright.sync_api import sync_playwright
errs=[];res=[]
def chk(n,c):res.append(c);print(('PASS ' if c else 'FAIL ')+n)
with sync_playwright() as p:
  b=p.chromium.launch();pg=b.new_page(viewport={'width':1400,'height':900})
  pg.on('pageerror',lambda e:errs.append(str(e)));pg.on('console',lambda m:m.type=='error' and errs.append(m.text[:200]));pg.on('dialog',lambda d:d.accept())
  pg.add_init_script("if(!sessionStorage.getItem('__l')){localStorage.clear();sessionStorage.setItem('__l','1');}")
  pg.goto('http://127.0.0.1:8090/babel-os.html');pg.wait_for_timeout(1500)
  J=pg.evaluate
  def c(sel):J(f"document.querySelector('{sel}').click()");pg.wait_for_timeout(300)
  def go(v):J(f"document.querySelector('#dock [data-go={v}]').click()");pg.wait_for_timeout(900)
  t=lambda:pg.inner_text('#view')
  go('finadm');chk('financeiro abre','Pedidos pendentes' in t())
  c('[data-act=fapcomp]');chk('modal comprovante',pg.is_visible('.modal'));c('[data-act=closelayer2]')
  c('[data-act=fapst][data-v=aprovado]');chk('aprovar pedido some da lista','Profissional' not in t())
  c('[data-act=fapst][data-v=recusado]');chk('recusar pedido','Nenhum pedido pendente' in t())
  c('[data-act=fatab][data-t=saques]');c('[data-act=fasrec]');pg.wait_for_timeout(300);chk('recusar saque (offline)','Nenhum saque pendente' in t())
  go('socioadm');chk('sócio abre','Link público' in t())
  c('[data-act=salink]');c('[data-act=sanovo]');chk('novo nível',J("document.querySelectorAll('[data-act=sadel]').length")==4)
  pg.fill('[data-saf=valor] >> nth=0','12');pg.press('[data-saf=valor] >> nth=0','Tab');pg.wait_for_timeout(300)
  chk('edita valor inline',J("[...document.querySelectorAll('[data-saf=valor]')].some(x=>x.value==='12')"))
  c('[data-act=satog]');c('[data-act=sadel]');chk('exclui nível',J("document.querySelectorAll('[data-act=sadel]').length")==3)
  c('[data-act=satab][data-t=rede]');pg.fill('#saBusca','ana');pg.wait_for_timeout(500);chk('busca rede','Ana Ribeiro' in t() and 'Marcos' not in t() and J("document.activeElement.id")=='saBusca')
  go('consadm');chk('consulta abre','Tipos ativos' in t())
  c('[data-act=catnovo]');pg.fill('#caNome','Antecedentes');pg.fill('#caCusto','2');pg.fill('#caPreco','8');c('[data-act=catsalvar]');chk('novo tipo','Antecedentes' in t())
  pg.fill('[data-capreco] >> nth=0','1');pg.press('[data-capreco] >> nth=0','Tab');pg.wait_for_timeout(300);chk('preço ao tenant abaixo do custo da API fica marcado',J("[...document.querySelectorAll('[data-capreco]')].some(x=>x.style.borderColor)"))
  c('[data-act=cattog]');c('[data-act=catdel]');chk('exclui tipo (soft)','Score de crédito' not in t())
  c('[data-act=catab][data-t=api]');pg.fill('#caProv','bigdata');pg.fill('#caToken','segredo123');c('[data-act=caolho]');chk('olho mostra token sem apagar campos',J("document.getElementById('caToken').type")=='text' and J("document.getElementById('caProv').value")=='bigdata')
  c('[data-act=caapisalvar]');pg.wait_for_timeout(300);chk('salva API','consulta_api_credencial_bigdata' in t())
  c('[data-act=catab][data-t=pacotes]');c('[data-act=cpnovo]');pg.fill('#cpNome','Mega');pg.fill('#cpValor','0');pg.fill('#cpCred','10');c('[data-act=cpsalvar]');chk('valida valor>0',pg.is_visible('.modal'))
  pg.fill('#cpValor','200');c('[data-act=cpsalvar]');chk('novo pacote','Mega' in t());c('[data-act=cpdel]');chk('exclui pacote',J("document.querySelectorAll('[data-act=cpdel]').length")==2)
  c('[data-act=catab][data-t=recargas]');c('[data-act=caapr]');pg.wait_for_timeout(300);chk('aprovar recarga','aprovada' in t())
  c('[data-act=carec]');chk('recusar recarga','recusada' in t())
  c('[data-act=cacreditar]');J("document.getElementById('caCrVal').value='30';document.getElementById('caCrMot').value='cortesia'");c('[data-act=cacrok]');pg.wait_for_timeout(300);chk('creditar fecha modal',not pg.is_visible('.modal'))
  c('[data-act=catab][data-t=rag]');pg.select_option('#caNicho','n3');pg.wait_for_timeout(300);chk('rag nicho','O que é score' in t())
  pg.fill('#caRagT','Prazo');pg.fill('#caRagC','A consulta sai em segundos.');c('[data-act=caragnovo]');chk('rag adiciona','A consulta sai em segundos.' in t())
  c('[data-act=caragdel]');chk('rag exclui','O que é score' not in t())
  b.close()
print('ERROS:',errs);print('TOTAL',sum(res),'/',len(res))
