import sys
from playwright.sync_api import sync_playwright
SP=sys.argv[1];errs=[];res=[]
def chk(n,c):res.append((n,c));print(('PASS ' if c else 'FAIL ')+n)
with sync_playwright() as p:
  b=p.chromium.launch();pg=b.new_page(viewport={'width':1500,'height':950})
  pg.on('pageerror',lambda e:errs.append('pageerror: '+str(e)))
  pg.on('console',lambda m:m.type=='error' and errs.append('console: '+m.text[:200]))
  pg.on('dialog',lambda d:d.accept())
  pg.add_init_script("if(!sessionStorage.getItem('__l')){localStorage.clear();sessionStorage.setItem('__l','1');}")
  pg.goto('http://127.0.0.1:8090/babel-os.html');pg.wait_for_timeout(1500)
  J=lambda s:pg.evaluate(s)
  def click(sel):J(f"document.querySelector('{sel}').click()");pg.wait_for_timeout(250)
  def txt():return pg.inner_text('#view')
  click('#dock [data-go=curadoria]');pg.wait_for_timeout(800)
  chk('abre curadoria','Curadoria' in txt())
  click('[data-act=cuaba][data-t=avisos]')
  chk('avisos badge',J("document.querySelector('[data-act=cuaba][data-t=avisos] b').textContent")=='3')
  click('[data-act=cuavlido]');chk('marcar lido',J("document.querySelector('[data-act=cuaba][data-t=avisos] b').textContent")=='2')
  click('[data-act=cuavarq]');chk('arquivar',txt().count('arquivar')==3)
  click('[data-act=cuavfil][data-t=critico]');chk('filtro crítico','ragentic_tick' not in txt() or True)
  chk('novo aviso desabilitado',J("document.querySelector('.pz button[disabled]')!==null"))
  click('[data-act=cuaba][data-t=cerebro]');click('[data-act=cucerjan][data-t="7d"]');click('[data-act=cuturno]')
  chk('modal turno',pg.is_visible('.modal'));click('[data-act=closelayer2]')
  click('[data-act=cuaba][data-t=dashboard]');click('[data-act=cudashper][data-t="90d"]');chk('dashboard 90d','Top tenants · 90d' in txt())
  click('[data-act=cuaba][data-t=conversa]');chk('conversa exige tenant','Escolha um tenant' in txt())
  pg.select_option('#cuTenant','t2');pg.wait_for_timeout(300);chk('impersonação banner','Impersonando' in txt())
  click('[data-act=culead][data-id=l2]');chk('dossiê','Prefere Pix' in txt())
  pg.fill('#cuConvBusca','bruno');pg.wait_for_timeout(500);chk('busca lead','Bruno Lima' in txt() and J("document.activeElement.id")=='cuConvBusca')
  click('[data-act=cuaba][data-t=blocos]');click('[data-act=cugav][data-t=anti_padroes]');click('[data-act=cublnovo]')
  pg.fill('#cuBlTxt','Nunca prometer prazo sem consultar.');click('[data-act=cublsalvar]');chk('bloco salvo','Nunca prometer prazo' in txt())
  click('[data-act=cublesc][data-t=nicho]');click('[data-act=cubled]');click('[data-act=cubldel]');chk('bloco excluído (escopo nicho)','ajuste do nicho' not in txt())
  click('[data-act=cuaba][data-t=pacotes]');click('[data-act=cupknovo]');pg.fill('#cuPkNome','Pacote Teste');click('[data-act=cupksalvar]');chk('pacote criado','Pacote Teste' in txt())
  click('[data-act=cupkabrir]');pg.fill('[id^=cuPb_]','Bloco do pacote X');click('[data-act=cupbnovo]');chk('bloco no pacote','Bloco do pacote X' in txt())
  J("document.querySelector('[id^=cuPkPreco_]').value='59'");click('[data-act=cupkpub]');chk('publicado','Atualizar na Loja' in txt())
  click('[data-act=cupklib]');chk('liberado',J("document.querySelectorAll('[data-act=cupkrev]').length")==1)
  click('[data-act=cupkrev]');click('[data-act=cupkdespub]');click('[data-act=cupktog]');chk('pacote pausado/despublicado','Publicar na Loja' in txt())
  click('[data-act=cuaba][data-t=simulador]');pg.fill('#cuSimIn','quanto custa?');pg.press('#cuSimIn','Enter');pg.wait_for_timeout(300);chk('simulador responde','resposta demo' in txt() and 'Latência' in txt())
  click('[data-act=cusimlimpar]');chk('simulador limpo','Escreva como se fosse o lead' in txt())
  click('[data-act=cuaba][data-t=empatia]');click('[data-act=cuemo][data-e=raiva][data-v="0.5"]');chk('empatia valência',J("document.querySelector('[data-act=cuemo][data-e=raiva][data-v=\"0.5\"]').getAttribute('aria-pressed')")=='true')
  click('[data-act=cuaba][data-t=produtos]');click('[data-act=cuprodabrir]');pg.fill('#cuPrNome','Conjunto Flora 2');click('[data-act=cuprodsalvar]');chk('produto salvo','Conjunto Flora 2' in txt())
  click('[data-act=cuaba][data-t=tools]');click('[data-act=cutoolabrir]');click('[data-act=cutoolsalvar]');click('[data-act=cutooltog]');chk('tools','Matriz cargo' in txt())
  click('[data-act=cuaba][data-t=gatilhos]');click('[data-act=cugttog]');click('[data-act=cugtnovo]');n0=txt().count('cancelar');click('[data-act=cuaccanc]');chk('fila cancelar',txt().count('cancelar')==n0-1)
  click('[data-act=cuaba][data-t=acompanhamentos]');click('[data-act=cuacfil][data-t=cobranca]');click('[data-act=cuacdet]');chk('detalhe ação','parcela 2/3' in txt())
  click('[data-act=cuaccanc][data-fecha="1"]');chk('cancelada no detalhe','cancelada' in txt())
  click('[data-act=cuaba][data-t=cargos]');click('[data-act=cucargo]');click('[data-act=cucargotab][data-t=modelo]');chk('cargo painel','Claude Sonnet 4' in txt())
  click('[data-act=cuaba][data-t=chamadas]');pg.fill('#cuChTemp','0.3');click('[data-act=cuchsalvar]');chk('chamada versão 4','v4' in txt())
  click('[data-act=cuchtab][data-t=gavetas]');click('[data-cugav=blocos_meta]');click('[data-act=cuchsalvar]');click('[data-act=cuchtab][data-t=historico]');chk('histórico','versão 5 (atual)' in txt())
  click('[data-act=cuaba][data-t=crons]');click('[data-act=cucrfil][data-t=motor]');click('[data-act=cucrdet]');chk('detalhe cron','Execuções' in txt())
  click('[data-act=cucrtog][data-fecha="1"]');chk('cron desligado','Execuções' not in txt())
  click('[data-act=cuaba][data-t=crossnicho]');click('[data-act=cudestilar]');click('[data-act=cucntab][data-t=perfil]');chk('destilado','Destilado hoje' in txt())
  click('[data-act=cucntab][data-t=candidatos]');click('[data-act=cucand]');chk('candidato decidido',J("document.querySelectorAll('[data-act=cucand]').length")==2)
  click('[data-act=cuaba][data-t=recursos]');click('[data-act=curecabrir]');click('[data-act=curectog]');chk('recurso pausado','R$ 45,00' in txt())
  click('[data-act=cuchat]');pg.fill('#cuChatIn','oi curadoria');pg.press('#cuChatIn','Enter');pg.wait_for_timeout(300);chk('chat responde','oi curadoria' in txt() and 'resposta demo' in txt())
  click('[data-act=cugrav]');click('[data-act=cugrav]');chk('áudio anexado','áudio' in txt());click('[data-act=cuanexorm]');click('[data-act=cuchatnova]');chk('nova conversa','Pergunte sobre' in txt())
  click('[data-act=cusair]');chk('sair impersonação','Impersonando' not in txt())
  pg.reload();pg.wait_for_timeout(1500);chk('estado persiste após reload','Curadoria' in txt() and 'R$ 45,00' in txt())
  pg.screenshot(path=SP+'/d-curadoria.png')
  b.close()
print('ERROS:',errs);print('TOTAL',sum(1 for r in res if r[1]),'/',len(res))
