// Arestas do grafo do motor vivo (48 arestas)
// Fonte: agent-output/analises/grafo-motor-vivo.json — gerado 2026-05-18

import type { ArestaMotorDados } from "./tipos";

export const ARESTAS_MOTOR: ArestaMotorDados[] = [
  { from: "zapi-in", to: "webhook-dedup", label: "HTTP POST Z-API payload" },
  { from: "webhook-dedup", to: "buffer-debounce", label: "msg nova (não grupo/presença/fromMe)" },
  { from: "buffer-debounce", to: "webhook-routing", label: "buffer pronto + texto combinado" },
  { from: "webhook-routing", to: "parse-body", label: "HTTP POST ragentic-processar-inline (service_role)" },
  { from: "parse-body", to: "canal-interno-branch", label: "ehFormatoInterno=true && !modo_teste" },
  { from: "parse-body", to: "detect-dono", label: "fluxo externo — verifica JWT" },
  { from: "detect-dono", to: "resolver-agente-tenant", label: "canal derivado → fluxo externo" },
  { from: "canal-interno-branch", to: "canal-interno-msg", label: "dono JWT válido" },
  { from: "canal-interno-msg", to: "canal-interno-historico", label: "msg inserida" },
  { from: "canal-interno-historico", to: "cargo-rag-first-interno", label: "histórico limpo" },
  { from: "cargo-rag-first-interno", to: "loop-llm-interno", label: "system prompt montado" },
  { from: "loop-llm-interno", to: "recall-entidade", label: "tool_call recall_entidade" },
  { from: "loop-llm-interno", to: "tools-mentor", label: "tool_call TOOLS_MENTOR" },
  { from: "recall-entidade", to: "loop-llm-interno", label: "resultado string → role=tool" },
  { from: "tools-mentor", to: "loop-llm-interno", label: "resultado JSON → role=tool" },
  { from: "loop-llm-interno", to: "canal-interno-persiste", label: "texto_final sem tool_calls" },
  { from: "canal-interno-persiste", to: "commandbar", label: "JSON {ok, mensagem, tool_calls}" },
  { from: "commandbar", to: "parse-body", label: "sb.functions.invoke ragentic (JWT user)" },
  { from: "resolver-agente-tenant", to: "resolver-conversa", label: "tenant_id + agente meta" },
  { from: "resolver-conversa", to: "token-proativo", label: "conversa_id resolvida" },
  { from: "token-proativo", to: "insere-user-msg", label: "msg real (não token proativo)" },
  { from: "token-proativo", to: "cargos-canal", label: "token proativo → pula insere msg" },
  { from: "insere-user-msg", to: "cargos-canal", label: "user msg persistida" },
  { from: "cargos-canal", to: "porteiro", label: "listaCargosTxt + msg do lead" },
  { from: "porteiro", to: "resolver-cargo-id", label: "classificacao {intencao, cargo_alvo, urgencia, resumo}" },
  { from: "resolver-cargo-id", to: "recall-rag-first", label: "tools + cargo_id + cargo_meta + diretrizes" },
  { from: "recall-rag-first", to: "recall-memoria", label: "trechoRag montado (top 5 blocos)" },
  { from: "recall-memoria", to: "heranca-crenca", label: "fatosLead + episodios" },
  { from: "heranca-crenca", to: "working-memory", label: "crença inicializada se necessário" },
  { from: "working-memory", to: "diretriz-bolha", label: "crença + intenção + compromissos lidos" },
  { from: "diretriz-bolha", to: "system-prompt", label: "_instrucaoBolha gerada" },
  { from: "system-prompt", to: "sintese-llm", label: "system + histórico + user msg" },
  { from: "sintese-llm", to: "tools-cargo-externo", label: "tool_calls do LLM" },
  { from: "tools-cargo-externo", to: "sintese-llm", label: "resultado tool → role=tool → próxima iteração" },
  { from: "sintese-llm", to: "pensamento-estruturado", label: "resposta_final com tag <pensamento_estruturado>" },
  { from: "pensamento-estruturado", to: "quebrar-bolhas", label: "resposta sem tag + pensamento parseado" },
  { from: "quebrar-bolhas", to: "enfileirar-bolhas", label: "bolhas[] (ou [silencio])" },
  { from: "enfileirar-bolhas", to: "trace-sintese", label: "bolhas enfileiradas" },
  { from: "trace-sintese", to: "extrator-s1", label: "trace gravado" },
  { from: "extrator-s1", to: "score-engajamento", label: "campos/tags/fatos extraídos e gravados" },
  { from: "score-engajamento", to: "intencoes-pendentes", label: "score calculado + engajamento_lead atualizado" },
  { from: "intencoes-pendentes", to: "episodica-inline", label: "intenção registrada" },
  { from: "episodica-inline", to: "crenca-upsert", label: "episódio gravado se relevante" },
  { from: "crenca-upsert", to: "response-http", label: "crença persistida" },
  { from: "response-http", to: "process-followups", label: "bolhas na caixa_saida_mensagens (lidas pelo cron 1min)" },
  { from: "process-followups", to: "zapi-out", label: "consumirOutbox → despacharBolhaViaZapi" },
  { from: "process-followups", to: "parse-body", label: "tokens proativos [X] → HTTP POST ragentic" },
  { from: "zapi-out", to: "zapi-in", label: "resposta entregue → lead responde (novo ciclo)" },
];
