// Nós do canal externo + ambos (lead/WhatsApp → motor)
// Fonte: agent-output/analises/grafo-motor-vivo.json — gerado 2026-05-18

import type { NoMotorDados } from "./tipos";

export const NOS_EXTERNO: NoMotorDados[] = [
  {
    id: "zapi-in",
    label: "Z-API → Webhook",
    canal: "externo",
    faz: "Recebe payload WhatsApp (texto/mídia/áudio/presença) via HTTP POST da Z-API",
    ativa_proximo: "Chama edge function webhook/index.ts",
    fonte_dado_real: "nao_grava (entrada externa — payload efêmero)",
    ref: "supabase/functions/webhook/index.ts:1",
  },
  {
    id: "webhook-dedup",
    label: "Webhook — Dedup + Presence",
    canal: "externo",
    faz: "SHA-256 hash da msg; RPC verificar_dedup_webhook. Rota presença (is_typing) → estado_digitacao UPSERT. fromMe → persiste em mensagens role=human. isGroup → descarta",
    ativa_proximo: "Se mensagem nova: buffer debounce",
    fonte_dado_real: "estado_digitacao.is_typing (UPSERT) | mensagens.role=human (INSERT) | traces: nao_grava",
    ref: "supabase/functions/webhook/index.ts:~100-270",
  },
  {
    id: "buffer-debounce",
    label: "Buffer Debounce (buffer_mensagens)",
    canal: "externo",
    faz: "RPC bufferar_mensagem_entrante agrupa rajada de msgs do lead. Persiste user msg em mensagens imediatamente (inbound_persistida). Poll (2s, max 90s) via verificar_buffer_pronto. Cancela bolhas antigas via substituir_caixa_saida_pendentes (barge-in).",
    ativa_proximo: "RPC reivindicar_buffer_mensagem → texto combinado → motor",
    fonte_dado_real: "mensagens.role=user (INSERT imediato webhook L~340) | buffer_mensagens (RPC bufferar_mensagem_entrante / reivindicar — tabela buffer_mensagens interna)",
    ref: "supabase/functions/webhook/index.ts:~340-420",
  },
  {
    id: "webhook-routing",
    label: "Webhook — Roteamento de Motor",
    canal: "externo",
    faz: "Chama ragentic-processar-inline (motor único do agente vivo) via HTTP POST service_role",
    ativa_proximo: "ragentic-processar-inline",
    fonte_dado_real: "nao_grava",
    ref: "supabase/functions/webhook/index.ts:~430-450",
  },
  {
    id: "parse-body",
    label: "ragentic — Parse Body + Branch Canal",
    canal: "ambos",
    faz: "Lê JSON: message/agente_id/phone/media_url/inbound_persistida/modo_teste/conversa_id/mensagem. Detecta ehFormatoInterno (!agente_id && !phone && conversa_id && mensagem). Se interno+!modo_teste → branch canal interno",
    ativa_proximo: "canal interno (processarCanalInterno) OU fluxo externo",
    fonte_dado_real: "nao_grava",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:142-178",
  },
  {
    id: "detect-dono",
    label: "detectarDonoLogado (identidade-interna.ts)",
    canal: "ambos",
    faz: "Verifica JWT Authorization header via supabase.auth.getUser(). Retorna {userId} se válido, null se ausente/inválido. Z-API/webhook não mandam JWT → null (externo). Chat-Teste manda JWT MAS modo_teste=true → externo (desempate !!dono && !modo_teste)",
    ativa_proximo: "informa canal (interno/externo) para canalConversa",
    fonte_dado_real: "nao_grava (consulta auth — efêmero)",
    ref: "supabase/functions/_shared/identidade-interna.ts (importado L20)",
  },
  {
    id: "resolver-agente-tenant",
    label: "Externo — Resolver Agente/Tenant",
    canal: "externo",
    faz: "SELECT agentes_usuario WHERE id=agente_id. Extrai user_id=tenant_id, nome_agente, identidade, tom_agente, calibragem_recall.empatia",
    ativa_proximo: "Resolver conversa",
    fonte_dado_real: "agentes_usuario (SELECT — read-only)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:200-215",
  },
  {
    id: "resolver-conversa",
    label: "Externo — Resolver/Criar Conversa",
    canal: "externo",
    faz: "Usa convIdInbound do webhook OU busca conversas ativas por phone+tenant_id. modo_teste: cria Lead de Teste + conversa channel=teste. Fix: se conversa teste sem lead_id, cria e linka",
    ativa_proximo: "Detecta token proativo",
    fonte_dado_real: "conversas (SELECT/INSERT) | leads (SELECT/INSERT — modo_teste Lead de Teste)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:216-330",
  },
  {
    id: "token-proativo",
    label: "Externo — Detecção Token Proativo",
    canal: "externo",
    faz: "Checa message.startsWith('[') && endsWith(']') && length<80. Se proativo: mapeia MAPA_TOKENS[token] → {cargo, situacao, query_rag}. Rota PLANEJAR_RETOMADA_* → LLM Gemma decide quando/angulo/assunto → INSERT acoes_agendadas + traces → retorna 200",
    ativa_proximo: "Carrega cargos do agente",
    fonte_dado_real: "acoes_agendadas (INSERT — PLANEJAR_RETOMADA_*) | traces (INSERT porteiro proativo)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:335-420",
  },
  {
    id: "insere-user-msg",
    label: "Externo — Insere msg user",
    canal: "externo",
    faz: "Se !inbound_persistida && !ehTokenProativo: INSERT mensagens role=user. Em modo_teste também persiste (histórico sidebar)",
    ativa_proximo: "Carrega cargos",
    fonte_dado_real: "mensagens (INSERT role=user)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:421-430",
  },
  {
    id: "cargos-canal",
    label: "Externo — Cargos + Filtro Canal",
    canal: "externo",
    faz: "SELECT cargos WHERE (agente_id=agente_id OR escopo=global) AND ativo=true ORDER BY ordem. derivarCanalConversa(!!dono && !modo_teste). Filtra canalElegivel(canal_atuacao, canalConversa). Carrega cargo anterior conversas.cargo_ativo_id. Monta listaCargosTxt para Porteiro",
    ativa_proximo: "Porteiro LLM",
    fonte_dado_real: "cargos (SELECT) | conversas.cargo_ativo_id (SELECT — read-only)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:432-530",
  },
  {
    id: "porteiro",
    label: "Porteiro — gemma-4-31b-it",
    canal: "externo",
    faz: "LLM classifica msg: {intencao, cargo_alvo, urgencia, resumo}. Usa listaCargosTxt (bússola+regras do tenant) como fonte de roteamento. Regra de inércia (só muda cargo se claramente outro). Proativo: pula Porteiro, usa classificacao do token",
    ativa_proximo: "INSERT traces tipo=porteiro → Resolve cargo_id",
    fonte_dado_real: "traces (INSERT tipo=porteiro: tenant_id/conversa_id/agente_id/decisao/latencia_ms/custo_tokens)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:540-620",
  },
  {
    id: "resolver-cargo-id",
    label: "Externo — resolverCargoId + carregarFerramentas",
    canal: "externo",
    faz: "resolverCargoIdPorAlvo(supabase, cargoAlvo, tenant_id) → cargo_id. carregarFerramentasDoCargo(supabase, cargoId) → array de tool schemas (cargo_ferramentas). Carrega cargo_meta (nome/objetivo/regras) + cargo_diretrizes (titulo/descricao ORDER BY ordem)",
    ativa_proximo: "UPDATE conversas.cargo_ativo_id + RAG-FIRST recall",
    fonte_dado_real: "cargo_ferramentas (SELECT via carregarFerramentasDoCargo) | cargos (SELECT nome/objetivo/regras) | cargo_diretrizes (SELECT) | conversas.cargo_ativo_id (UPDATE)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:622-680 | _shared/tools-internas.ts:resolverCargoIdPorAlvo",
  },
  {
    id: "recall-rag-first",
    label: "RAG-FIRST — recuperarBlocosRagFirst",
    canal: "externo",
    faz: "gerarEmbeddingQuery (Cohere embed-v4.0 1536d) → RPC busca_hibrida_conhecimento (FTS+halfvec+RRF, 3 escopos: tenant/nicho/global) → rerankCohere v3.5 → ponderação por escopo → top 5 blocos. INSERT trace tipo=ferramenta ferramenta=recall_pre_sintese",
    ativa_proximo: "Recall memória",
    fonte_dado_real: "blocos_conhecimento (via RPC busca_hibrida_conhecimento — SELECT) | traces (INSERT tipo=ferramenta)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:684-715 | _shared/tools-internas.ts:recuperarBlocosRagFirst",
  },
  {
    id: "recall-memoria",
    label: "Recall Memória — recuperarMemoriaLead",
    canal: "externo",
    faz: "gerarEmbeddingQuery → RPC busca_hibrida_memoria_lead (p_match_count=10) + busca_hibrida_memoria_episodica (p_match_count=5) em paralelo. INSERT trace tipo=ferramenta ferramenta=leitura_memoria_pre_sintese",
    ativa_proximo: "Herança de crença (A8) + leitura working memory",
    fonte_dado_real: "memoria_lead (via RPC busca_hibrida_memoria_lead — SELECT) | memoria_episodica (via RPC busca_hibrida_memoria_episodica — SELECT) | traces (INSERT)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:718-755 | _shared/recall-memoria.ts:recuperarMemoriaLead",
  },
  {
    id: "heranca-crenca",
    label: "A8 — Herança Crença (conversa anterior 7d)",
    canal: "externo",
    faz: "Se crenca_conversa vazia E lead conversou com agente nos últimos 7d: copia belief da última crenca_conversa anterior com flag herdada_de. INSERT trace ferramenta=herdar_crenca_conversa_anterior",
    ativa_proximo: "Leitura working memory (crença + intenção pendente + compromissos)",
    fonte_dado_real: "crenca_conversa (SELECT verificação + INSERT herança) | conversas (SELECT anteriores do lead) | traces (INSERT)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:740-800",
  },
  {
    id: "working-memory",
    label: "Working Memory — crença + intenção + EMA",
    canal: "externo",
    faz: "SELECT crenca_conversa (belief/resumo/proxima_intencao/estilo_lead) + intencoes_pendentes (proxima_intencao/acao_pretendida/motivo/plano) em Promise.all. SELECT compromissos_ativos (view unifica acoes_agendadas+compromissos+contratos, por conversa, limit 5)",
    ativa_proximo: "Diretriz bolha",
    fonte_dado_real: "crenca_conversa (SELECT) | intencoes_pendentes (SELECT) | compromissos_ativos (VIEW SELECT)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:800-845",
  },
  {
    id: "diretriz-bolha",
    label: "Diretriz Bolha — selecionarDiretrizBolha (v54)",
    canal: "externo",
    faz: "Query = resumo_porteiro|intencao|urgencia|msg. gerarEmbeddingQuery → RPC busca_hibrida_diretriz_bolha (p_top_k=3). Fallback: diretriz_bolha_blocos WHERE tag_sempre_ativo=true ORDER tenant>nicho>global. Retorna {quantidade_sugerida, chars_medio_sugerido, motivo, contexto, escopo}",
    ativa_proximo: "Montagem system prompt",
    fonte_dado_real: "diretriz_bolha_blocos (SELECT via RPC ou fallback direto) | nao_grava",
    ref: "supabase/functions/_shared/diretriz-bolha.ts:selecionarDiretrizBolha | index.ts:~960-975",
  },
  {
    id: "system-prompt",
    label: "Montagem System Prompt (10 blocos)",
    canal: "externo",
    faz: "Concatena em ordem: blocoTemporal (data BRT) + blocoIdentidade (nome/cargo/tom) + blocoBussola (objetivo/regras cargo) + blocoDiretrizesCargo (cargo_diretrizes) + blocoEmpatia (calibragem sliders) + blocoCrenca (resumo/proxIntencao/passoPrev) + blocoFatos (memoria_lead top 10) + blocoEpisodios (memoria_episodica top 5) + blocoPensamento (intencoes_pendentes) + blocoEMA (compromissos_ativos) + instrução + _instrucaoBolha (diretriz bolha) + trechoRag (blocos RAG-first)",
    ativa_proximo: "Síntese LLM + loop tool-calling",
    fonte_dado_real: "nao_grava (montagem em memória)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:840-1000",
  },
  {
    id: "sintese-llm",
    label: "Síntese — gemini-3.1-flash-lite (MAX_ITER=3)",
    canal: "externo",
    faz: "chamarLLM com model=gemini-3.1-flash-lite, temp=0.6, max_tokens=1400, tools=cargo_ferramentas. Loop até MAX_ITER_TOOL_CALLING=3: se tool_calls → despacharFerramenta → INSERT trace tipo=ferramenta → continua. Resposta inclui <pensamento_estruturado> JSON ao final",
    ativa_proximo: "Extração pensamento_estruturado + quebrarEmBolhas",
    fonte_dado_real: "traces (INSERT tipo=ferramenta por tool chamada) | tabelas das ferramentas (ver nó transversal tools)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:1005-1080",
  },
  {
    id: "pensamento-estruturado",
    label: "A3 — Extração Pensamento Estruturado",
    canal: "externo",
    faz: "Regex extrai <pensamento_estruturado>JSON</pensamento_estruturado> (tag fechada ou aberta/truncada). Valida acao_pretendida contra enum 8 valores. Strip da tag da resposta final. Fallback derivado do porteiro se parse falhar",
    ativa_proximo: "Normaliza \\n → quebras reais → quebrarEmBolhas",
    fonte_dado_real: "nao_grava (processamento em memória)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:1085-1155",
  },
  {
    id: "quebrar-bolhas",
    label: "quebrarEmBolhas (_shared/bolhas.ts)",
    canal: "externo",
    faz: "Quebra resposta_final por linhas em branco duplas (parágrafos). Detecta [silencio]/[no-reply] → agente não responde. Retorna {bolhas: string[]}",
    ativa_proximo: "Enfileirar bolhas em caixa_saida_mensagens (ou mensagens direto em modo_teste)",
    fonte_dado_real: "nao_grava (processamento em memória)",
    ref: "supabase/functions/_shared/bolhas.ts:quebrarEmBolhas | index.ts:1158",
  },
  {
    id: "enfileirar-bolhas",
    label: "Enfileirar Bolhas → caixa_saida_mensagens",
    canal: "externo",
    faz: "Para cada bolha: calcula delay humanizado (comprimento×50ms ± jitter, min 800ms max 8s). scheduled_at = t0+filaMs. INSERT caixa_saida_mensagens {tenant_id, conversation_id, status=pendente, content, bubble_order, scheduled_at, delay_calculado_ms, engagement_level, carga:{typing_ms, origem}}. modo_teste: INSERT mensagens direto",
    ativa_proximo: "INSERT trace tipo=sintese → Extrator S1 + Score",
    fonte_dado_real: "caixa_saida_mensagens (INSERT por bolha) | mensagens (INSERT em modo_teste role=assistant)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:1160-1195",
  },
  {
    id: "trace-sintese",
    label: "Trace Síntese",
    canal: "externo",
    faz: "INSERT traces tipo=sintese: resposta_preview/tools_usadas/cargo/bolhas/latencia_ms/custo_tokens_in/custo_tokens_out",
    ativa_proximo: "Extrator Sistema 1 (S1)",
    fonte_dado_real: "traces (INSERT tipo=sintese)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:1197-1210",
  },
  {
    id: "extrator-s1",
    label: "Extrator Sistema 1 (S1) — gemma-4-31b-it",
    canal: "externo",
    faz: "Se !ehTokenProativo && cargoId && conv.lead_id: LLM Gemma extrai {campos_prancheta, campos_evidencia, tags (8 namespaces), fatos (max 3, conf>=0.6)}. Anti-alucinação A6: descarta campo sem evidência>=3chars. Merge leads.dados_ficha (não sobrescreve com null). A1: INSERT fatos em memoria_lead (gate anti-dup ilike 60% palavras). INSERT traces tipo=ferramenta ferramenta=extrair_dados_ficha",
    ativa_proximo: "Score + Engajamento",
    fonte_dado_real: "leads.dados_ficha (UPDATE merge) | leads.tags (UPDATE array) | memoria_lead (INSERT fatos novos OU UPDATE confianca corroborado) | traces (INSERT tipo=ferramenta)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:1215-1540",
  },
  {
    id: "score-engajamento",
    label: "Score Lead + Engajamento",
    canal: "externo",
    faz: "Computa scoreLead = 70×coberturaPrancheta + 20×min(1,totalMsgs/5) + 10×urgenciaPeso. UPDATE conversas.score_lead. calcularEngajamento → UPSERT engajamento_lead (nivel/pontuacao/comprimento_medio/tendencia). UPDATE leads.temperatura_lead. INSERT traces tipo=ferramenta ferramenta=score_calculado",
    ativa_proximo: "Insere intencoes_pendentes",
    fonte_dado_real: "conversas.score_lead (UPDATE) | engajamento_lead (UPSERT) | leads.temperatura_lead (UPDATE) | traces (INSERT)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:1545-1620",
  },
  {
    id: "intencoes-pendentes",
    label: "INSERT intencoes_pendentes",
    canal: "externo",
    faz: "Se !ehTokenProativo: INSERT intencoes_pendentes com intencao/dados{cargo_alvo, urgencia, resumo_porteiro, tools_usadas, blocos_recuperados, campos_extraidos, tags_sugeridas, score_lead, pensamento estruturado 6 campos A3, métricas qualidade A1/A2/A6/A8}",
    ativa_proximo: "A2 memória episódica inline",
    fonte_dado_real: "intencoes_pendentes (INSERT)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:1625-1665",
  },
  {
    id: "episodica-inline",
    label: "A2 — Memória Episódica Inline",
    canal: "externo",
    faz: "Se !ehTokenProativo && conv.lead_id: detecta episódio relevante (ação forte/urgência alta/sentimento/fatos_novos>=2). Guard: intervalo mínimo 3 turnos do último episódio. INSERT memoria_episodica {episodio_resumo, gancho, emocao, outcome, turno_inicio/fim, relevancia, decay_factor, embedding_status=pendente}. INSERT trace",
    ativa_proximo: "Upsert crença_conversa",
    fonte_dado_real: "memoria_episodica (INSERT) | traces (INSERT ferramenta=memoria_episodica_inline)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:1668-1740",
  },
  {
    id: "crenca-upsert",
    label: "Upsert crenca_conversa",
    canal: "externo",
    faz: "SELECT crenca_conversa.id. Se existe: UPDATE belief (merge) + resumo_agente. Se não: INSERT {belief:{intencao,cargo,urgencia,bolhas_ultimo_turno,blocos_recuperados,tools_usadas,atualizado_em}}",
    ativa_proximo: "JSON Response HTTP 200",
    fonte_dado_real: "crenca_conversa (UPDATE ou INSERT)",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:1745-1785",
  },
  {
    id: "response-http",
    label: "Response HTTP 200",
    canal: "externo",
    faz: "Retorna {reply, mensagens:bolhas, conversation_id}. Em modo_teste: inclui trace completo inline (intencao/cargo/urgencia/pensamento/compromissos/fatos/episodios/score/tokens/modelos)",
    ativa_proximo: "webhook lê chatData.mensagens.length → processar-acompanhamentos (outbox)",
    fonte_dado_real: "nao_grava",
    ref: "supabase/functions/ragentic-processar-inline/index.ts:1788-1858",
  },
  {
    id: "process-followups",
    label: "processar-acompanhamentos — Worker Outbox + Ações",
    canal: "externo",
    faz: "Roda via pg_cron (1 min). RPC liberar_zumbis (status=processando >15min). RPC pegar_proxima_acao_agendada (SKIP LOCKED, max 50). Loop: guard conversa+agent_enabled. Gate horário comercial. Guard compromisso ativo (RPC existe_compromisso_ativo). Mapeia action_type → token [X] → POST ragentic-processar-inline. UPDATE acoes_agendadas.status=executado/falhou. consumirOutbox: lê caixa_saida_mensagens pendentes → despacharBolhaViaZapi → Z-API → lead",
    ativa_proximo: "ragentic-processar-inline (tokens proativos) | Z-API (bolhas da caixa_saida)",
    fonte_dado_real: "acoes_agendadas (UPDATE status) | caixa_saida_mensagens (UPDATE status=enviada) | mensagens (INSERT assistente via despacharBolhaViaZapi) | leads_campanha (UPDATE phase/last_contact_at)",
    ref: "supabase/functions/processar-acompanhamentos/index.ts:1-380 | outbox-consumer.ts",
  },
  {
    id: "zapi-out",
    label: "Z-API → WhatsApp Lead",
    canal: "externo",
    faz: "despacharBolhaViaZapi: sendZApi/sendZApiMedia com typing_ms de humanização. Envia bolha ao lead via Z-API REST API. UPDATE caixa_saida_mensagens.status=enviada+dispatched_at. INSERT mensagens role=assistant (entregue_at)",
    ativa_proximo: "Fim do fluxo externo (Z-API entrega ao WhatsApp do lead)",
    fonte_dado_real: "caixa_saida_mensagens (UPDATE status=enviada) | mensagens (UPDATE entregue_at)",
    ref: "supabase/functions/processar-acompanhamentos/outbox-consumer.ts",
  },
];
