// Telas do app (gerado do NAV do babel-os.html em 02/10): [id, nome, apelidos]
'use strict';
module.exports = [
  ["inicio", "Início", ["inicio", "home", "esfera"]],
  ["conversas", "Conversas", ["conversa", "whatsapp", "mensagens"]],
  ["notas", "Notas", []],
  ["contatos", "Contatos", []],
  ["clientes", "Clientes", []],
  ["contratos", "Contratos", []],
  ["financeiro", "Financeiro", ["financeiro", "cobranca", "cobrancas", "dinheiro", "caixa"]],
  ["agenda", "Agenda", ["agenda", "calendario", "compromissos"]],
  ["agente", "Agente", ["agente", "aurora"]],
  ["chattreino", "Chat Treino", ["chat treino", "treino", "treinar"]],
  ["cargosag", "Cargos do agente", ["cargos do agente"]],
  ["loja", "Loja", ["loja", "vitrine"]],
  ["lojababel", "Loja Babel", ["loja babel", "plano", "assinatura"]],
  ["equipe", "Equipe", []],
  ["meudia", "Meu dia", ["meu dia"]],
  ["qualidade", "Qualidade", ["qualidade"]],
  ["ajustes", "Ajustes", ["ajustes", "configuracoes", "configuracao"]],
  ["empresa", "Empresa", []],
  ["calculadora", "Calculadora", []],
  ["juridico", "Jurídico", []],
  ["contab", "Contabilidade", ["contabilidade"]],
  ["credito", "Crédito", ["credito"]],
  ["rh", "RH", []],
  ["reino", "Reino", []],
  ["email", "E-mail", []],
  ["estoque", "Estoque", []],
  ["produtos", "Produtos", []],
  ["textos", "Textos", []],
  ["socio", "Parceiro", ["socio"]],
  ["marketing", "Marketing", []],
  ["mentor", "Mentor", []],
  ["consulta", "Consulta", []],
  ["campanha", "Campanhas", ["campanha", "campanhas"]],
  ["rifas", "Rifas", []],
  ["reuniao", "Reunião", ["reuniao", "reunioes"]],
  ["maquete", "Maquete-RPG", ["maquete"]],
  ["nichos", "Nichos", []],
  ["lojaadm", "Loja Admin", ["loja admin"]],
  ["appsadm", "Aplicativos", ["aplicativos"]],
  ["juradm", "Jurídico Admin", ["juridico admin"]],
  ["gestao", "Gestão", ["gestao"]],
  ["curadoria", "Curadoria", ["curadoria"]],
  ["dash", "Dashboard", ["dashboard", "painel"]],
  ["reunadm", "Reuniões Admin", ["reunioes admin"]],
  ["apar", "Aparência", ["aparencia"]],
  ["cargos", "Cargos", []],
  ["controle", "Controle", ["controle"]],
  ["finadm", "Financeiro (admin)", ["financeiro admin"]],
  ["socioadm", "Parceiro (admin)", ["socio admin"]],
  ["consadm", "Consulta (admin)", ["consulta admin"]],
  ["tenants", "Tenants", ["tenants", "clientes da babel"]]
];
